vaadin.launch-browser=true
spring.application.name=demo

# BANCO EM MEMÓRIA (H2) - Não precisa de servidor externo!
spring.datasource.url=jdbc:h2:mem:notification_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configurações do Mailtrap (ou seu servidor de E-mail)
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=seu_usuario
spring.mail.password=sua_senha

# Configurações das Filas do RabbitMQ
amqp.queue.transaction-completed=q.transaction-completed
amqp.exchange.notification=ex.notification
amqp.routing-key.transaction-completed=rk.transaction-completed
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration